### ISSUE TITLE
[Full app display][No icon]

### ISSUE THREAD

**Issue by YahiaHatab** [huhridge/huh-spicetify-extensions#61] opened 2023-06-22 11:44 UTC
**Describe the bug**
The extension has no icon, like its not downloaded.

**To Reproduce**
Steps to reproduce the behavior: Downloaded the extension after the new spotify update, and there is no icon.

**Expected behavior**
The extension icon should show up.

**Console Errors**
To check the console, run `spicetify enable-devtools` in the terminal, and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> and check the console.

**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53063646/935ccd1f-d3b4-43d7-972d-398a7ce4144e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Spotify Version: Spotify for Windows (32 bit)1.2.13.661.ga588f749
 - Spicetify Version: Spicetify v2.20.1

**Additional context**

**Comment by iamxyntho** [comment] 2023-06-22 14:13
Yes, I confirm that it's definitely happening. For me, the workaround is reinstalling the extension every time I want to use it, which is pretty annoying :)

**Comment by iamxyntho** [comment] 2023-06-22 14:26
Strange, now it's suddenly working. Why is there uncertainity in the working of this script?

**Comment by YahiaHatab** [comment] 2023-06-22 15:08
> Strange, now it's suddenly working. Why is there uncertainity in the working of this script?

It didn't work with me at all, i tried to close spotify and reopen it again and even reinstalling the extension but still.
I checked the console, and it says "to load resource: net::ERR_NAME_NOT_RESOLVED".

**Comment by iamxyntho** [comment] 2023-06-22 17:40
Just a little update: I found out whenever you `spicetify enable-devtools`, it magically appears (for me) so I can't basically even see the error. Can you post a screenshot of the console error in here?

**Comment by iamxyntho** [comment] 2023-06-22 17:43
I am not able to reproduce the error as you describe it, `spicetify enable-devtools` basically makes it impossible to debug since the moment I run it, the extension runs fine. Strange innit?

**Comment by iamxyntho** [comment] 2023-06-22 17:48
I also believe this has to do something with Spicetify not with the extension. As you described that it happens only after the latest **Spotify** update, I assume something in the binaries broke Spicetify? Basically for which this extension _may not_ have anything to do with the problem as it is Spicetify based I guess.

**Comment by iamxyntho** [comment] 2023-06-22 17:50
Update: I runned `Spicetify update` and that seems to solve the problem for me, I don't have to `Spicetify enable-devtools` now. If the issue has been solved, you may kindly close it now.

**Comment by YahiaHatab** [comment] 2023-06-22 18:12
Tried the "spicetify update" but still same issue, and when i check the the console it shows the same error.
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53063646/baa4ec99-8616-43c2-9e79-cddb22f553f0)

**Comment by YahiaHatab** [comment] 2023-06-22 18:19
> I also believe this has to do something with Spicetify not with the extension. As you described that it happens only after the latest **Spotify** update, I assume something in the binaries broke Spicetify? Basically for which this extension _may not_ have anything to do with the problem as it is Spicetify based I guess.

I am sure of this too, since the extension just got updated recently (21st of june), so it should be compatible with the new spotify version.

**Comment by YahiaHatab** [comment] 2023-06-22 18:35
Update: 
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53063646/155bfb1a-ff41-43df-bca4-be48d1713052)
I think the problem is that spicetify can't fetch the extension, i tried multiple extensions and there was the same problem, they are not working at all. 
I had to download them manually so they could work.

**Comment by iamxyntho** [comment] 2023-06-23 08:55
> I think the problem is that spicetify can't fetch the extension
That's correct! Can you check if the specific `maifest.json` was loaded for the extension?

**Comment by iamxyntho** [comment] 2023-06-23 08:57
<img width="948" alt="image" src="https://github.com/huhridge/huh-spicetify-extensions/assets/79999919/8fa38791-aed5-4df7-b296-4ddc8b673df6">
For me, it's loaded correctly. Can you specify the version of Spicetify you're using?

**Comment by iamxyntho** [comment] 2023-06-23 09:02
<img width="140" alt="image" src="https://github.com/huhridge/huh-spicetify-extensions/assets/79999919/0fad76f9-7192-4562-a4f2-9e63334e85ec">
Also for me, I can't seem to find the fullAppDisplayMod.js file in the scripts section in frames of application tab. Is spicetify on your end, mistaking fullAppDisplayMod.js to be a core spicetify js file?

**Comment by YahiaHatab** [comment] 2023-06-23 11:59
> > I think the problem is that spicetify can't fetch the extension
> 
> That's correct! Can you check if the specific `maifest.json` was loaded for the extension?

Same as everything. 
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53063646/bfe731cf-d059-4c23-8480-dd6186705638)

**Comment by YahiaHatab** [comment] 2023-06-23 12:01
> <img alt="image" width="948" src="https://user-images.githubusercontent.com/79999919/248221679-8fa38791-aed5-4df7-b296-4ddc8b673df6.png"> For me, it's loaded correctly. Can you specify the version of Spicetify you're using?

I am using 2.20.1 version by spicetify, which should be the latest version.

**Comment by YahiaHatab** [comment] 2023-06-23 12:04
> Also for me, I can't seem to find the fullAppDisplayMod.js file in the scripts section in frames of application tab. Is spicetify on your end, mistaking fullAppDisplayMod.js to be a core spicetify js file?

That maybe the problem, as the extension is in the scripts folder unlike you. 
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53063646/876c8bdd-d19f-46d8-99f2-c6f48d402b91)

**Comment by iamxyntho** [comment] 2023-06-23 12:48
> That maybe the problem

I believe it **is** the problem on your side, I didn't even manage to recreate it.

**Comment by iamxyntho** [comment] 2023-06-23 13:47
For me, I can confirm once again that enabling devtools just solves the issue magically.

**Comment by huhridge** [comment] 2023-12-06 15:10
weird issue, seemed to be with spicetify itself

**Closed by huhridge** 2023-12-06 15:10 UTC
Labels: bug
