### ISSUE TITLE
[full screen icon does not appear][BUG]

### ISSUE THREAD

**Issue by fareselash** [huhridge/huh-spicetify-extensions#63] opened 2023-06-26 15:05 UTC
**Describe the bug**
The full screen icon does not appear and the extension does not work.

**Desktop (please complete the following information):**
 - OS:11
 - Spotify Version: latest
 - Spicetify Version: latest

**Comment by iamxyntho** [comment] 2023-06-26 17:38
Duplicate of #61

**Comment by huhridge** [comment] 2023-12-06 15:09
should be fixed!

**Closed by huhridge** 2023-12-06 15:09 UTC
Labels: bug
